---
title: "git_01"
author: "Peter Dang"
date: "Spring 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
The farmhouse lingers, though averse to square    
With the new city street it has to wear    
A number in. But what about the brook    
That held the house as in an elbow-crook?    
I ask as one who knew the brook, its strength    
And impulse, having dipped a finger length    
And made it leap my knuckle, having tossed    
A flower to try its currents where they crossed.    
The meadow grass could be cemented down    
From growing under pavements of a town;    
The apple trees be sent to hearth-stone flame.    
Is water wood to serve a brook the same?    
How else dispose of an immortal force    
No longer needed? Staunch it at its source    
With cinder loads dumped down? The brook was thrown    
Deep in a sewer dungeon under stone    
In fetid darkness still to live and run —    
And all for nothing it had ever done       
Except forget to go in fear perhaps.    
No one would know except for ancient maps    
